declare module '*.scss' {
  // 悔しいけどこうやって使う
  export const title: string
  export const container: string
  export const tag: string
  export const link: string
  export const profile: string
  export const career: string
  export const marquee: string
  export const emoji: string
  export const header: string
  export const name: string
  export const map: string
  export const footer: string
  export const card: string
  export const blog: string
  export const date: string
  export const notfound: string
  export const blogs: string
  export const search: string
  export const index: string
  export const privacy: string
  export const background: string
  export const console: string
  export const contents: string
  export const zuruzuru: string
  export const main: string
  export const more: string
  export const invite: string
  export const related: string
  export const limit: string
  export const menu: string
}
