name: deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          npm install -g yarn
          yarn
          yarn deploy
