name: deploy
on:
  workflow_dispatch:

jobs:
  deploy-ghpages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
        run: git checkout HEAD^
      - name: setup yarn & build
        run: |
          npm install -g yarn
          yarn
          yarn ogp
          yarn build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: deploy
